name: check

on:
  push:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'
      - name: Install Dependencies
        run: npm install
      - name: spell-check
        run: npx cspell lint *
